### ISSUE TITLE
Fonts auf Safari

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#1]
Die Schrift Futura (Titel) wird nicht korrekt angezeigt auf Safari

**Comment by dfringeli** [comment]
Schau mal rein, ich hab kein iOS/Safari
Hab otf und ttf types für futura hinzugefügt
könnte klappen

**Comment by angie-graphics** [comment]
nope, leider keine Veränderung auf iOS

**Comment by dfringeli** [comment]
Hast du es auch im "Inkognitomodus" von safari versucht?
wegen cache und so..
wie beim z-index

**Comment by angie-graphics** [comment]
jup und auf handy auch noch..

**Comment by angie-graphics** [comment]
hab' noch was gefunden, vielleicht hilfts? https://css-tricks.com/forums/topic/font-face-not-working-in-only-safari/

**Comment by angie-graphics** [comment]
ahh mist ne. ist ja gar kein webfont

**Comment by dfringeli** [comment]
Kannst es anschauen, hab es korrigiert 💯 
Mein Fehler war ich habe die Schrift "Futura Condensed PT" im @font-face nur "Futura" genannt, der Einfachheit halber.
Dann hat Safari "Futura" Schrift geladen anstatt die im @font-face tatsächliche "Futura Condesed PT".

**Comment by angie-graphics** [comment]
auch das klappt! yeah.. danke vielmals
