### ISSUE TITLE
Header top margin verrutscht

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#10]
Der Header ist nach unten verrutscht so dass nun der Hintergrund hervorscheint:

![image](https://user-images.githubusercontent.com/46542480/51785236-f8ffe480-2154-11e9-941f-1673692fbf74.png)

bräuchte wohl einen negativen top-wert und dafür noch ein padding, damit das logo nicht zu weit nach oben geht:

.fixed-top {
    position: fixed;
    top: -14px;
    padding-top: 14px;
    right: 0;
    left: 0;
    z-index: 1030;
}

----

oder wenn dies allgemein problematisch ist mit den schrägen hintergründen, wäre es evt. besser mit SVG's oben und unten eines blocks?

**Comment by dfringeli** [comment]
Jaa SVGs wären eine Lösung.
Jedoch ist dieser Spalt jetzt geschichte und nicht sichtbar.
Hab das damals glaub zu früh hochgeladen..

**Comment by angie-graphics** [comment]
jup sieht gut aus nun
