### ISSUE TITLE
Squeezed images in IE

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#11]
von anderen habe ich gehört, dass im IE die Anzeige gequetscht sei. Da ich kein IE habe auf Mac, musste ich dies mit BrowserStack prüfen. Dort werden die Bilder hauptsächlich gequetscht statt beschnitten:

![2](https://user-images.githubusercontent.com/46542480/52225883-c029e300-28ab-11e9-90bd-cf183b3a5d4e.png)

![1](https://user-images.githubusercontent.com/46542480/52225886-c1f3a680-28ab-11e9-81a6-3b958d7afd95.png)

**Comment by dfringeli** [comment]
Habe dieses Problem bei den Posts sowie beim Slider beachtet und behoben.

**Comment by angie-graphics** [comment]
getestet mit browserstack (IE) und edge
scheint gut zu sein :-)
