### ISSUE TITLE
flickr account einrichten

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#13]
bitte einen flickr account einrichten und analog tvzwingen einbinden auf der webseite auf einer noch versteckten zusatzseite "Fotos" oder so.

Am ETF wird es einen Stand geben wo man als Gruppe Fotos machen kann und dieses Foto wird dann dort hochgeladen.

**Comment by angie-graphics** [comment]
Mail an: etf@ktf21.ch

**Comment by dfringeli** [comment]
Ist gut.
Braucht es eine Ansicht der Alben wie hier: https://www.flickr.com/photos/tvzwingen/albums
oder genügt ein ein Photostream: https://www.flickr.com/photos/tvzwingen/ und http://tvzwingen.ch/fotos/ ?

Ein Plugin für einen einfachen Photostream gibt es.
Ein Wordpress Plugin mit Albenansicht hab ich noch nicht gefunden, etvl. gibt es ein kostenpflichtiges. ansonsten würde ich das plugin mit der flickr API selbst schreiben, was viel aufwand wäre.

**Comment by dfringeli** [comment]
apropos kostenpflichtig: flickr ist neu auch kostenpflichtig ab einer anzahl von 1000 Fotos. es wären 50$ oder ca. 60 Franken im Jahr. Dann hat man ein Pro Account.
Hat man kein Pro Account und mehr als 1000 Fotos werden sie einfach gelöscht.

**Comment by angie-graphics** [comment]
Ein Fotostream reicht aus. Das wäre nur für das ETF gedacht, damit wir vom Stand aus direkt Bilder auf die Webseite laden können.

Betreffend Gebühren ist das voll blöd 👎 - hmm ich denke aber wir werden nicht auf 1000 Fotos kommen für den Stream. Deshalb denke ich reicht die gratis Version aus.

Danke dir für die Recherche!

**Comment by dfringeli** [comment]
zum anschauen: https://ktf21.ch/fotos/
siehe mail
