### ISSUE TITLE
Untermenü - Aufzählungszeichen

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#15]
S andere ticket isch leider scho zue, drum e neus.

Chame bi de Untermenü no e Ufzelligszeiche mache, damits nid so i dr Luft hangt?

evt. das do: **→**

![image](https://user-images.githubusercontent.com/46542480/56412863-d4179b00-6285-11e9-8116-fefc3cbd61ab.png)

**Comment by dfringeli** [comment]
Hab es umgesetzt.
Doch ich habe > anstatt den Pfeil verwendet
Ebenfalls die Schriftgrösse verkleinert
Ist dies so gut oder soll ich den Pfeil verwenden? Ich fand > besser :)

**Comment by angie-graphics** [comment]
tipp top! danke
