### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#16]
Wo kann ich den Inhalt der 404 Seite anpassen?
Falls ich das nicht kann, bitte wie folgt anpassen:

**Hoppla! Die Site gits leider nid oder nümi.**
Vielleicht kann dir die Suche weiterhelfen:

_Im Suchfeld:_ "Suche nach..."

**Comment by dfringeli** [comment]
done: https://ktf21.ch/noni

ebenfalls auch Spacing zwischen Blöcken und Navigation verbessert

**Comment by angie-graphics** [comment]
kannst du bitte aus den 2 h1-titeln einen machen im gleichen block und diesen hellgrün?

dankeeeee

**Comment by dfringeli** [comment]
Done
