### ISSUE TITLE
Form Buttons

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#18]
Für die WP Formulare hast du eine Klasse erstellt für die Buttons "btn-ktf2021-white" > funzt super

"btn-ktf2021-blue" scheint es auch zu geben, jedoch ohne Hover Effekt.
und "btn-ktf2021-green" ist gar nicht vorhanden.

Kannst du die noch ergänzen?

Dankeeee

**Comment by dfringeli** [comment]
verwende: ktf2021-button { black | white | green | blue }

d.h. für einen grünen Link:
`<a class="ktf2021-button green" ... />`
oder für blauen Button:
`<button class="ktf2021-button blue" ... />`

Hoffe das passt

**Comment by angie-graphics** [comment]
hmm die habe ich schon probiert, dann kommt bei mir im formular ein grauer button mit falscher schrift.
![image](https://user-images.githubusercontent.com/46542480/59147939-3d07cd80-8a02-11e9-8dd9-8172c00c126a.png)

**Comment by dfringeli** [comment]
Es war dass das CSS von WPForms stärker war und dies übernommen wurde..
Ich habe !importants zu `ktf2021-button color` hinzugefügt nun siehts gut aus
![image](https://user-images.githubusercontent.com/33898687/59148616-8577b900-8a0b-11e9-8cf6-0a073fd09981.png)

![image](https://user-images.githubusercontent.com/33898687/59148622-91fc1180-8a0b-11e9-8685-4bec2cf7bb36.png)

**Comment by angie-graphics** [comment]
juppiii - funktioniert, danke
