### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#2]
müssten noch ergänzt werden, wenn möglich mit Webfonts und Rollover Effekt, analog Prototyp :-)

kann statisch sein, aber den Web-Font muss man noch einbauen :-)

**Comment by dfringeli** [comment]
Habe den Block KTF2021 Social Media Buttons erstellt und unter https://ktf21.ch gerade auch ein Beispiel.
Da die Accounts noch nicht existieren, habe ich es so gelöst, dass man eine Link eingeben kann, zu welchem der Social Media Button verweisen soll.
Wird kein Link angegeben, so wird der Button auch nicht angezeigt.
Die Eingabe des Links wird nicht überprüft!

Ich habe Facebook, Instagram, Youtube und Flickr vorgesehen - fehlt noch eine Plattform?

**Comment by angie-graphics** [comment]
die gsehnd schomol sehr guet us. 
plattformmässig sind mal die wichtigsten drauf. bitte neue tests nicht auf der startseite machen, sondern auf einer unveröffentlichten seite. wir fangen ja nun an, die domain zu streuen, wäre unprofessionell, wenn die besucher dann auf die tvzwingen seite kommen.

ich habe deshalb den block auf home mal entfernt und auf diese seite gemacht: 
https://ktf21.ch/?page_id=959&preview=true

kann man diese noch grösser machen, vor allem auf desktop? analog prototyp?

**Comment by dfringeli** [comment]
sorry, werde dies nicht mehr machen.

Habe die Icons responsive gemacht: https://ktf21.ch/?page_id=959&preview=true
Mobile: sowie bis hin (font-size: 3em)
Desktop: grösser wie bis hin (font-size: 5em)

**Comment by angie-graphics** [comment]
uf safari isches immerno chli uf desktop: 
![image](https://user-images.githubusercontent.com/46542480/58120920-808ec900-7c06-11e9-876f-13b4735430a2.png)

FF & Chrome gsehnd top us

**Comment by dfringeli** [comment]
Ich habe es beim Kollegen auf Safari ansehen können und es sieht bei ihm gut aus:
![image](https://user-images.githubusercontent.com/33898687/58254725-a97c9e80-7d6b-11e9-800c-ce422744f2c4.png)
Ich habe letzens LiteSpeed Cache installiert und ebenfalls aufgrund des Caches ein dasselbe Problem gehabt - dass es ein css einfach nicht neu geladen hat. Ich glaube dies ist das selbe Problem.
Kannst nochmal schauen, obs jetzt läuft.

**Comment by angie-graphics** [comment]
hast recht, war ein caching problem.. nun siehst auch bei mir gut aus 👍
