### ISSUE TITLE
Facebook - Domains verifizieren

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#20]
für das Facebook Konto müssen wir die Domain verifizieren, ansonsten werden die Bilder teilweise nicht korrekt angezeigt beim Teilen.

![image](https://user-images.githubusercontent.com/46542480/59549971-79d54680-8f65-11e9-8859-6896e8f1000e.png)

ktf2021.ch:  facebook-domain-verification=xis28g5gez3d54m5mq3r44q46kgizk
ktf21.ch: facebook-domain-verification=1z1bv1li3oj8ywcq8jh1fkq25e7vxm

**Comment by dfringeli** [comment]
Hab die TXT Records hinzugefügt

**Comment by angie-graphics** [comment]
perfekt, danke
