### ISSUE TITLE
Slogan integrieren

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#27]
Hi Dominik

Auf Mario's Wunsch hin sollen wir auf der Webseite den Slogan noch integrieren.

Seine Idee:

![image](https://user-images.githubusercontent.com/46542480/77455432-22201180-6dfa-11ea-9770-433afd100d89.png)

Ich hatte mal einen Entwurf der Webseite mit dem Slogan im Slider drin (halb transparent):
![image](https://user-images.githubusercontent.com/46542480/77455484-3532e180-6dfa-11ea-934a-89f7aa8e3c1b.png)

Könntest du die einfachere Version umsetzen?

Text:

mir sy turnfescht! bisch du's au?

**Comment by dfringeli** [comment]
Ja ich schaue es an und setze es um.

**Comment by dfringeli** [comment]
Ist umgesetzt.

Du findest es auf Home

Hast du noch Feedback/Anassungen?

**Comment by angie-graphics** [comment]
Chrome & FF: 
- Schrift darf grösser sein (ca. 60px) 
- Möglich die Schrift in die Neigung zu setzen des Sliders? Falls die Schrift dann zerreisst, gerade lassen.
- Auf mobile aktuell nicht sichtbar

Safari: 
- hier ist der schriftzug unter dem slider in schwarz statt auf dem slider:

![image](https://user-images.githubusercontent.com/46542480/78421838-31edf000-765b-11ea-880b-331afda7b60d.png)

**Comment by dfringeli** [comment]
## Schriftgrösse
Schriftgrösse i.O. mache ich h1 anstatt h2, dann ist sie mit h1 64px gross. Dann muss es aber über die Bullets, weil der Text so lang ist.

## Neigung
Ich hatte den Schriftzug in der Neigung. Es verreisst nicht, aber ich persönlich fand es komisch den Text schräg zu lesen, vor allem, weil der "Save The Date.." wieder gerade ist.

Kurz im DOM angepasst würde es etwa so aussehen:
![image](https://user-images.githubusercontent.com/33898687/78453739-f6bbe300-7693-11ea-80d7-2fb7158b125c.png)
Was denkt Du? was soll ich machen?

## Mobile
Auf mobile finde ich hat es fast kein platz, trotz h3 mit 28px, deswegen hab ich es nur auf Desktop.

Kurz im DOM angepasst würde es etwa so aussehen:
![image](https://user-images.githubusercontent.com/33898687/78453655-67aecb00-7693-11ea-9862-1e25c2350628.png)

Man müsste es fast zentriert in die Mitte tun. Dann sieht man das Bild fast nicht mehr.
Was denkt Du? was soll ich machen?

## Safari
Ich hatte dieses Problem jetzt gerade auch in Chrome. Bei mir hatte es mit dem Cache zu tun. Dann wars wieder gut.

**Comment by angie-graphics** [comment]
Schriftgrösse: h1 wäre iO, ja > bitte umsetzen

Neigung: ok, gerade lassen
Mobile: ok, weglassen

safari: war auch cache > alles iO :-)

**Comment by dfringeli** [comment]
ist angepasst und online

**Comment by angie-graphics** [comment]
tipp top! vielen Dank, passt so :-)
