### ISSUE TITLE
Mobile: langer Text umbrechen

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#4]
Der Text bricht zumindest auf iPhone nicht um.
Wir allenfalls hyphens benötigt?

Siehe Beispiel:

p {
  hyphens: auto;
  -webkit-hyphens: auto;
  -webkit-hyphenate-limit-chars: auto 3;
  -webkit-hyphenate-limit-lines: 4;
  -ms-hyphens: auto;
  -ms-hyphenate-limit-chars: auto 3;
  -ms-hyphenate-limit-lines: 4;
}

![img_5670](https://user-images.githubusercontent.com/46542480/51185784-5637a280-18d8-11e9-8bcb-8f7dad949d0d.PNG)
![img_5672](https://user-images.githubusercontent.com/46542480/51185785-5637a280-18d8-11e9-9338-faf29cfebebc.PNG)
![img_5673](https://user-images.githubusercontent.com/46542480/51185786-5637a280-18d8-11e9-9578-ee4096430725.PNG)

**Comment by dfringeli** [comment]
verwendete word-break: break-all;
hyphens: auto; wird fast nicht unterstützt.. ist abhängig von der eingestellten Sprache

**Comment by angie-graphics** [comment]
wird nun umgebrochen, jedoch ohne Bindestrich auf iPhone:![image1](https://user-images.githubusercontent.com/46542480/51524352-30595300-1e2e-11e9-977b-c82fb54de416.png)

![image2](https://user-images.githubusercontent.com/46542480/51524357-32bbad00-1e2e-11e9-8f97-b1bb0e6dcce5.png)
