### ISSUE TITLE
Mobile: Navigation linksbündig

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#5]
In der mobile Navigation sind die Spalten eingerückt auf iPhone:

![img_5668](https://user-images.githubusercontent.com/46542480/51185853-88490480-18d8-11e9-95df-78941ca9d306.PNG)

**Comment by dfringeli** [comment]
Sie sind nicht eingerückt, sondern sind mit justify-content-center zentriert.
Aufgrund der unterschiedlich langen Menu-Namen sind sie unterschiedlich "zentriert" (eingerückt)
werde es fixen

**Comment by dfringeli** [comment]
Soo irgendwie hannis gschafft, dank padding-left: 33%;
mit flex zum zentriere hannis nit ahnebecho..
Ig hoff es längt

**Comment by angie-graphics** [comment]
5% läng uf mobile wenns linksbündig isch, suscht wird de text abgschnitte
