### ISSUE TITLE
Mobile: Slider pagination - falscher z-index

### ISSUE THREAD

**Issue by angie-graphics** [dfringeli/ktf2021#6]
In der mobile Navigation sind die paginations vom Slider sichtbar:

![img_5667](https://user-images.githubusercontent.com/46542480/51185895-a7e02d00-18d8-11e9-92fd-6ce6e7d06d68.PNG)

**Comment by dfringeli** [comment]
isch gmacht für search und navigation

**Comment by angie-graphics** [comment]
funzt nach cache leere :-)
danke

**Comment by dfringeli** [comment]
Jaa genau
blöder css cache..
