### ISSUE TITLE
Menu mit Unterpunkte

### ISSUE THREAD

**Issue by dfringeli** [dfringeli/ktf2021#8]
Bis jetzt wird nur die erste Ebene von Menu Punkten dargestellt

**Comment by dfringeli** [comment]
isch gmacht
ig haa unterpünkt vomene menu eifach dargstellt und chli vo links ihgruckt

**Comment by angie-graphics** [comment]
hmm das gseht komisch us.. 
1. isches uf mobile zvill abstand vo links. siehe bild unde
2. uf desktop erkennt me nid dass es unterpünkt si.. seht us als wär eifach d darstellig durenand grote. 

sorry, do bruchts e anderi lösig. suscht lömers wäg und hoffe, dass es nid vill site wird gä ;-)

**Comment by angie-graphics** [comment]
bispiel iphone: 
![img_5838](https://user-images.githubusercontent.com/46542480/51546848-53532980-1e65-11e9-96e7-c10a8b704061.PNG)
